# Default state for all rules
default: true

# MD013/line-length - Line length
MD013: false

# MD033/no-inline-html - Inline HTML
MD033:
  allowed_elements:
    - col
    - colgroup
    - em
    - table
    - tbody
    - td
    - th
    - thead
    - tr
    # mathml tags
    - math
    - mfrac
    - mi
    - mn
    - mo
    - mrow
    - mspace
    - msqrt
    - msup
    - mtable
    - mtd
    - mtext
    - mtr

# MD059/Link text should be descriptive
MD059: false
