title: EHR Settings
x-stoplight:
  id: m0iw4p0mf24nb
type: object
properties:
  enabled:
    type: boolean
    description: Enable or disable the EHR integration
  facility:
    $ref: ./ehrfacility.v1.yaml
  sourceId:
    type: string
  destinationIds:
    $ref: ./ehrdestinations.v1.yaml
required:
  - enabled
  - sourceId
  - destinationIds
