title: EHR Settings
x-stoplight:
  id: m0iw4p0mf24nb
type: object
properties:
  enabled:
    type: boolean
    description: Enable or disable the EHR integration
  facility:
    $ref: ./ehrfacility.v1.yaml
  sourceId:
    type: string
  destinationIds:
    $ref: ./ehrdestinations.v1.yaml
  procedureCodes:
    $ref: ./ehrprocedures.v1.yaml
  mrnIdType:
    type: string
    x-stoplight:
      id: x74orwp43yu91
    minLength: 1
  provider:
    type: string
    x-stoplight:
      id: z31vhe9hbaqrn
    enum:
      - xealth
      - redox
required:
  - enabled
  - sourceId
  - procedureCodes
  - mrnIdType
  - provider
