title: Patient Count Settings
type: object
properties:
  hardLimit:
    description: The hard limit for the clinic patient count where new patients cannot be created
    $ref: './patientCountLimit.v1.yaml'
  softLimit:
    description: The soft limit for the clinic patient count where new patients may still be created
    $ref: './patientCountLimit.v1.yaml'
