openapi: 3.0.0
info:
  title: Confirmation API
  version: '1.0'
  description: |-
    The Tidepool API is an HTTP REST API used by Tidepool clients use to communicate with the Tidepool Platform.

    For more information, see the [Getting Started](../docs/quick-start.md) section.
  termsOfService: https://developer.tidepool.org/terms-of-use/
  contact:
    name: API Support
    url: https://support.tidepool.org/
    email: support@tidepool.org
  license:
    name: BSD-2-Clause
    url: https://github.com/tidepool-org/hydrophone/blob/master/LICENSE
  x-tidepool-service: https://github.com/tidepool-org/hydrophone

servers:
  - url: 'http://localhost:8080'
    description: local development
  - url: 'https://dev1.dev.tidepool.org'
    description: dev1
  - url: 'https://qa1.development.tidepool.org'
    description: qa1
  - url: 'https://qa2.development.tidepool.org'
    description: qa2
  - url: 'https://external.integration.tidepool.org'
    description: integration
  - url: 'https://api.tidepool.org'
    description: production

tags:
  - name: Internal
    description: >-
      APIs intended for internal use by Tidepool.
  - name: Confirmations
    description: >-
      Manage confirmations for account creation, sharing invites, etc.

paths:
  '/confirm/send/signup/{userId}':
    parameters:
      - $ref: '#/components/parameters/userId'
    post:
      operationId: SendAccountSignupConfirmation
      summary: Send Account Signup Confirmation
      description: >-
        Sends account signup confirmation email.
      requestBody:
        $ref: '#/components/requestBodies/ConfirmationUpsert'
      responses:
        '200':
          $ref: '#/components/responses/ConfirmationSuccess'
        '400':
          $ref: '#/components/responses/ConfirmationError'
        '401':
          $ref: '#/components/responses/ConfirmationError'
        '403':
          $ref: '#/components/responses/ConfirmationError'
        '500':
          $ref: '#/components/responses/ConfirmationError'
      tags:
        - Confirmations
      security:
        - sessionToken: []

  '/confirm/resend/signup/{email}':
    parameters:
      - $ref: '#/components/parameters/email'
    post:
      operationId: ResendAccountSignup
      summary: Resend account signup confirmation email
      description: >-
        If a user didn't receive the confirmation email and logs in, they're
        directed to the confirmation-required page which can offer to resend the
        confirmation email.
      responses:
        '200':
          $ref: '#/components/responses/ConfirmationSuccess'
        '404':
          $ref: '#/components/responses/ConfirmationError'
        '500':
          $ref: '#/components/responses/ConfirmationError'
      tags:
        - Confirmations

  '/confirm/accept/signup/{key}':
    parameters:
      - $ref: '#/components/parameters/key'
    put:
      operationId: ConfirmAccountSignup
      summary: Accept Account Signup
      description: >-
        Marks the account as having been verified.
        This would be PUT by the web page at the link in the signup email.
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Acceptance'
      responses:
        '200':
          $ref: '#/components/responses/ConfirmationSuccess'
        '400':
          $ref: '#/components/responses/ConfirmationError'
        '409':
          $ref: '#/components/responses/ConfirmationError'
        '500':
          $ref: '#/components/responses/ConfirmationError'
      tags:
        - Confirmations

  '/confirm/dismiss/signup/{userId}':
    parameters:
      - $ref: '#/components/parameters/userId'
    put:
      operationId: DismissAccountSignup
      summary: Dismiss Account Signup
      description: >-
        In the event that someone uses the wrong email address, the receiver
        could explicitly dismiss a signup
      requestBody:
        $ref: '#/components/requestBodies/ConfirmationLookup'
      responses:
        '200':
          $ref: '#/components/responses/ConfirmationSuccess'
        '400':
          $ref: '#/components/responses/ConfirmationError'
        '404':
          $ref: '#/components/responses/ConfirmationError'
      tags:
        - Confirmations

  '/confirm/signup/{userId}':
    parameters:
      - $ref: '#/components/parameters/userId'
    get:
      operationId: GetAccountSignupConfirmation
      summary: Get Account Signup Confirmation
      description: >-
        Fetch latest account signup confirmation for the provided userId
      responses:
        '200':
          $ref: '#/components/responses/Confirmation'
        '400':
          $ref: '#/components/responses/ConfirmationError'
        '401':
          $ref: '#/components/responses/ConfirmationError'
        '404':
          $ref: '#/components/responses/ConfirmationError'
        '500':
          $ref: '#/components/responses/ConfirmationError'
      tags:
        - Confirmations
      security:
        - sessionToken: []
    post:
      operationId: UpsertAccountSignupConfirmation
      summary: Upsert Account Signup Confirmation
      description: >-
        Add or refresh an account signup confirmation for the provided userId
      requestBody:
        $ref: '#/components/requestBodies/ConfirmationUpsert'
      responses:
        '200':
          $ref: '#/components/responses/Confirmation'
        '400':
          $ref: '#/components/responses/ConfirmationError'
        '403':
          $ref: '#/components/responses/ConfirmationError'
        '404':
          $ref: '#/components/responses/ConfirmationError'
        '500':
          $ref: '#/components/responses/ConfirmationError'
      tags:
        - Confirm
      security:
        - sessionToken: []

    put:
      operationId: CancelAccountSignupConfirmation
      summary: Cancel Account Signup
      description: >-
        Cancels the account signup.
      requestBody:
        $ref: '#/components/requestBodies/ConfirmationLookup'
      responses:
        '200':
          $ref: '#/components/responses/ConfirmationSuccess'
        '400':
          $ref: '#/components/responses/ConfirmationError'
        '401':
          $ref: '#/components/responses/ConfirmationError'
        '403':
          $ref: '#/components/responses/ConfirmationError'
        '404':
          $ref: '#/components/responses/ConfirmationError'
      tags:
        - Confirmations

  '/confirm/forgot/{email}':
    parameters:
      - $ref: '#/components/parameters/email'
    post:
      operationId: SendPasswordReset
      summary: Send Password Reset Email
      description: >-
        If the request is correctly formed, always returns a 200, even if the
        email address was not found (this way it can't be used to validate email
        addresses).

        If the email address is found in the Tidepool system, this will:
          - Create a confirm record and a random key
          - Send an email with a link containing the key
      responses:
        '200':
          $ref: '#/components/responses/ConfirmationSuccess'
        '400':
          $ref: '#/components/responses/ConfirmationError'
      tags:
        - Confirmations

  '/confirm/accept/forgot':
    put:
      operationId: AcceptPasswordChange
      summary: Accept password change
      description: >-
        Accept the password change

        This endpoint will be invoked by the lost password screen with the key that was included in the URL of the lost password screen.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Password'
      responses:
        '200':
          $ref: '#/components/responses/ConfirmationError'
        '400':
          $ref: '#/components/responses/ConfirmationError'
        '401':
          $ref: '#/components/responses/ConfirmationError'
        '404':
          $ref: '#/components/responses/ConfirmationError'
      tags:
        - Confirmations

  '/confirm/send/invite/{userId}':
    parameters:
      - $ref: '#/components/parameters/userId'
    post:
      operationId: SendCareTeamInvite
      summary: Send Invitation to Join Care Team
      description: >-
        Sends an invitation to join the care team of the user identified by `userId`.
      requestBody:
        content:
          application/json:
            schema:
              $ref: './confirm/models/invitation.v1.yaml'
      responses:
        '200':
          $ref: '#/components/responses/Confirmation'
        '400':
          $ref: '#/components/responses/ConfirmationError'
        '401':
          $ref: '#/components/responses/ConfirmationError'
        '500':
          $ref: '#/components/responses/ConfirmationError'
      security:
        - sessionToken: []
      tags:
        - Confirmations

  '/confirm/accept/invite/{userId}/{invitedBy}':
    parameters:
      - $ref: '#/components/parameters/userId'
      - $ref: '#/components/parameters/invitedByUser'
    put:
      operationId: AcceptCareTeamInvite
      summary: Accept Invitation to Join Care Team
      description: >-
        Accepts the invitation to join a care team.
      requestBody:
        $ref: '#/components/requestBodies/ConfirmationLookup'
      responses:
        '200':
          $ref: '#/components/responses/ConfirmationSuccess'
        '400':
          $ref: '#/components/responses/ConfirmationError'
        '403':
          $ref: '#/components/responses/ConfirmationError'
        '404':
          $ref: '#/components/responses/ConfirmationError'
        '500':
          $ref: '#/components/responses/ConfirmationError'
      tags:
        - Confirmations

  '/confirm/invite/{userId}':
    parameters:
      - $ref: '#/components/parameters/userId'
    get:
      operationId: GetSentInvitations
      summary: Get Pending Care Team Invitations
      description: >-
        Returns the still-pending invitations for an account you own or are an admin of.

        These are the invitations you have sent that have not been accepted.
        There is no way to tell if an invitation has been ignored.
      responses:
        '200':
          $ref: '#/components/responses/ConfirmationList'
        '400':
          $ref: '#/components/responses/ConfirmationError'
        '401':
          $ref: '#/components/responses/ConfirmationError'
        '500':
          $ref: '#/components/responses/ConfirmationError'
      tags:
        - Confirmations
      security:
        - sessionToken: []

  '/confirm/invitations/{userId}':
    parameters:
      - $ref: '#/components/parameters/userId'
    get:
      operationId: GetReceivedInvitations
      summary: Get Received Care Team Invitations
      description: >-
        Get list of received invitations for logged in user.
        These are invitations that have been sent to this user but not yet acted upon.
      responses:
        '200':
          $ref: '#/components/responses/ConfirmationList'
        '400':
          $ref: '#/components/responses/ConfirmationError'
        '401':
          $ref: '#/components/responses/ConfirmationError'
      tags:
        - Confirmations
      security:
        - sessionToken: []

  '/confirm/dismiss/invite/{userId}/{invitedBy}':
    parameters:
      - $ref: '#/components/parameters/userId'
      - $ref: '#/components/parameters/invitedByUser'
    put:
      operationId: DismissInvite
      summary: Dismiss Care Team Invitation
      description: >-
        Declines the invitation to join a care team.
      requestBody:
        $ref: '#/components/requestBodies/ConfirmationLookup'
      responses:
        '200':
          $ref: '#/components/responses/ConfirmationSuccess'
        '400':
          $ref: '#/components/responses/ConfirmationError'
        '401':
          $ref: '#/components/responses/ConfirmationError'
        '404':
          $ref: '#/components/responses/ConfirmationError'
        '500':
          $ref: '#/components/responses/ConfirmationError'
      tags:
        - Confirmations
      security:
        - sessionToken: []

  '/confirm/{userId}/invited/{invitedBy}':
    parameters:
      - $ref: '#/components/parameters/userId'
      - $ref: '#/components/parameters/invitedByEmail'
    put:
      operationId: CancelInvite
      summary: Cancel Care Team Invitation
      description: >-
        Cancels an invitation that has been sent to an email address.
      responses:
        '200':
          $ref: '#/components/responses/ConfirmationSuccess'
        '400':
          $ref: '#/components/responses/ConfirmationError'
        '401':
          $ref: '#/components/responses/ConfirmationError'
        '500':
          $ref: '#/components/responses/ConfirmationError'
      tags:
        - Confirmations
      security:
        - sessionToken: []

components:
  schemas:
    Acceptance:
      $ref: './confirm/models/acceptance.v1.yaml'

    TidepoolUserId:
      $ref: './common/models/tidepooluserid.yaml'

    ClinicId:
      $ref: './clinic/models/clinicid.v1.yaml'

    EmailAddress:
      $ref: ./common/models/emailaddress.v1.yaml

    DateTime:
      $ref: ./common/models/datetime.v1.yaml

    Key:
      $ref: ./confirm/models/key.v1.yaml

    Password:
      $ref: ./common/models/password.v1.yaml

    Birthday:
      $ref: './common/models/birthday.v1.yaml'

    Confirmation:
      $ref: ./confirm/models/confirmation.v1.yaml

  parameters:
    userId:
      $ref: './common/parameters/tidepooluserid.yaml'

    email:
      $ref: './confirm/parameters/email.v1.yaml'

    key:
      $ref: './confirm/parameters/key.v1.yaml'

    invitedByUser:
      $ref: './confirm/parameters/invitedbyuser.v1.yaml'

    invitedByEmail:
      $ref: './confirm/parameters/invitedbyemail.v1.yaml'

  securitySchemes:
    sessionToken:
      $ref: './common/security/tidepoolsessiontoken.v1.yaml'

  requestBodies:
    ConfirmationLookup:
      content:
        'application/json':
          schema:
            $ref: './confirm/models/lookup.v1.yaml'

    ConfirmationUpsert:
      content:
        'application/json':
          schema:
            $ref: './confirm/models/upsert.v1.yaml'

  responses:
    Confirmation:
      description: 'Single confirmation'
      content:
        'application/json':
          schema:
            $ref: './confirm/models/confirmation.v1.yaml'

    ConfirmationList:
      description: 'List of confirmations'
      content:
        'application/json':
          schema:
            $ref: './confirm/models/list.v1.yaml'

    ConfirmationSuccess:
      description: 'Success'

    ConfirmationError:
      description: 'Error'
      content:
        'application/json':
          schema:
            $ref: './confirm/models/error.v1.yaml'
