openapi: 3.0.0
info:
  title: Export API
  version: '1.0'
  description: |-
    The Tidepool API is an HTTP REST API used by Tidepool clients use to communicate with the Tidepool Platform.

    For more information, see the [Getting Started](../docs/quick-start.md) section.
  termsOfService: https://developer.tidepool.org/terms-of-use/
  contact:
    name: Tidepool Api Support
    url: https://support.tidepool.org
    email: support@tidepool.org
  license:
    name: BSD-2-Clause
    url: https://github.com/tidepool-org/export/blob/master/LICENSE
  x-tidepool-service: https://github.com/tidepool-org/export

servers:
  - url: 'https://external.integration.tidepool.org'
    description: integration
  - url: 'https://api.tidepool.org'
    description: production
  - url: 'https://dev1.dev.tidepool.org'
    description: dev1
  - url: 'https://qa1.development.tidepool.org'
    description: qa1
  - url: 'https://qa2.development.tidepool.org'
    description: qa2

tags:
  - name: Internal
    description: >-
      APIs intended for internal use by Tidepool.
  - name: Export
    description: >-
      Enable bulk export of diabetes data from user's Tidepool account.

paths:
  '/export/{userId}':
    parameters:
      - $ref: './common/parameters/tidepooluserid.yaml'
    get:
      operationId: ExportUserData
      summary: Export user data
      description: >-
        Exports the diabetes data from user identified by `userId`, from `startDate` to `endDate`, in the requested `format`.
        Either a Tidepool session token, or a restricted token must be supplied.
      parameters:
        - $ref: './export/parameters/startdate.v1.yaml'
        - $ref: './export/parameters/enddate.v1.yaml'
        - $ref: './export/parameters/format.v1.yaml'
        - $ref: './export/parameters/glucoseunits.v1.yaml'
      responses:
        '200':
          description: >-
            User data exported in the requested `format`.
          headers:
            Content-Disposition:
              $ref: './common/headers/contentdisposition.v1.yaml'
          content:
            'application/json':
              schema:
                $ref: './export/models/json.v1.yaml'
            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':
              schema:
                $ref: './export/models/excel.v1.yaml'
        '400':
          $ref: './common/responses/badrequest.v1.yaml'
        '401':
          $ref: './common/responses/unauthorized.v1.yaml'
        '403':
          $ref: './common/responses/forbidden.v1.yaml'
        '500':
          $ref: './common/responses/servererror.v1.yaml'

      security:
        - sessionToken: []
        - restrictedToken: []
      tags:
        - Export
        - Internal
  '/export/report/{userId}':
    parameters:
      - $ref: './common/parameters/tidepooluserid.yaml'
    post:
      operationId: ExportUserReport
      summary: Export user report
      description: >-
        User report exported in with the requested options.
      requestBody:
        content:
          application/json:
            schema:
              $ref: './export/models/reportrequest.v1.yaml'
      responses:
        '200':
          description: A PDF report for the given user
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '400':
          $ref: './common/responses/badrequest.v1.yaml'
        '401':
          $ref: './common/responses/unauthorized.v1.yaml'
        '403':
          $ref: './common/responses/forbidden.v1.yaml'
        '500':
          $ref: './common/responses/servererror.v1.yaml'
      security:
        - sessionToken: []
        - restrictedToken: []
      tags:
        - Export
        - Internal
components:
  securitySchemes:
    sessionToken:
      $ref: './common/security/tidepoolsessiontoken.v1.yaml'

    restrictedToken:
      $ref: './common/security/tidepoolrestrictedtoken.v1.yaml'
