openapi: 3.0.0
info:
  title: General API
  version: '1.0'
  description: |-
    The Tidepool API is an HTTP REST API used by Tidepool clients use to communicate with the Tidepool Platform.

    For more information, see the [Getting Started](../docs/quick-start.md) section.
  termsOfService: https://developer.tidepool.org/terms-of-use
  contact:
    name: API Support
    url: https://support.tidepool.org/
    email: support@tidepool.org
  license:
    name: BSD-2-Clause
    url: https://github.com/tidepool-org/shoreline/blob/master/LICENSE
  x-tidepool-service: https://github.com/tidepool-org/jellyfish

servers:
  - url: 'https://external.integration.tidepool.org'
    description: integration
  - url: 'https://api.tidepool.org'
    description: production
  - url: 'https://dev1.dev.tidepool.org'
    description: dev1
  - url: 'https://qa1.development.tidepool.org'
    description: qa1
  - url: 'https://qa2.development.tidepool.org'
    description: qa2

tags:
  - name: Internal
    description: >-
      APIs intended for internal use by Tidepool.
  - name: General
    description: >-
      General utility APIs.

paths:
  /info:
    get:
      operationId: GetMinimumClientVersions
      summary: Get Minimum Client Versions
      description: >-
        Returns minimum Tidepool client application versions.
        If a client application detects that it is older than the minimum version returned by this API, it should notify the user and terminate promptly.
        This API requires no authentication or authorization.
      responses:
        '200':
          $ref: '#/components/responses/ClientVersions'
      tags:
        - General
        - Internal
      x-tidepool-service: https://github.com/tidepool-org/jellyfish

components:
  responses:
    ClientVersions:
      description: 'Tidepool Minimum Client Versions'
      content:
        'application/json':
          schema:
            $ref: './common/models/minimumclientversions.v1.yaml'
