openapi: 3.0.0
info:
  title: Data Summary API
  version: '1.0'
  description: |-
    The Tidepool API is an HTTP REST API used by Tidepool clients use to communicate with the Tidepool Platform.

    For more information, see the [Getting Started](../docs/quick-start.md) section.
  contact:
    name: Tidepool
    url: 'https://www.tidepool.org'
    email: support@tidepool.org
  termsOfService: 'https://developer.tidepool.org/terms-of-use/'
  license:
    name: 'BSD 2-Clause "Simplified" License'
    url: 'https://github.com/tidepool-org/summary/blob/master/LICENSE'
  x-tidepool-service: https://github.com/tidepool-org/summary

servers:
  - url: 'https://external.integration.tidepool.org'
    description: integration
  - url: 'https://api.tidepool.org'
    description: production
  - url: 'https://dev1.dev.tidepool.org'
    description: dev1
  - url: 'https://qa1.development.tidepool.org'
    description: qa1
  - url: 'https://qa2.development.tidepool.org'
    description: qa2

security:
  - sessionToken: []

tags:
  - name: Internal
    description: >-
      APIs intended for internal use by Tidepool.
  - name: Summary
    description: |-
      Summary Data

      This API is for a component within the `data` service that calculates summary statistics for user accounts.
      These routes are mostly executed by the `task` and `clinic-worker` services.

paths:
  '/v1/summaries/{summaryType}/{userId}':
    parameters:
      - $ref: '#/components/parameters/summaryType.v5'
      - $ref: '#/components/parameters/userId'
    get:
      summary: Get User Summary
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./summary/models/summary.v5.yaml
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: GetSummary
      description: Retrieve a summary by user id
      x-internal: true
      tags:
        - Summary
        - Internal

components:
  securitySchemes:
    sessionToken:
      $ref: './common/security/tidepoolsessiontoken.v1.yaml'
    serverToken:
      $ref: './common/security/tidepoolservertoken.v1.yaml'
  parameters:
    summaryType.v5:
      name: summaryType
      in: path
      required: true
      schema:
        $ref: ./summary/models/summaryType.v5.yaml
    userId:
      name: userId
      in: path
      required: true
      schema:
        $ref: ./common/models/tidepooluserid.yaml
