openapi: 3.0.0
info:
  title: Data Summary API
  version: '1.0'
  description: |-
    The Tidepool API is an HTTP REST API used by Tidepool clients use to communicate with the Tidepool Platform.

    For more information, see the [Getting Started](../docs/quick-start.md) section.
  contact:
    name: Tidepool
    url: 'https://www.tidepool.org'
    email: support@tidepool.org
  termsOfService: 'https://developer.tidepool.org/terms-of-use/'
  license:
    name: 'BSD 2-Clause "Simplified" License'
    url: 'https://github.com/tidepool-org/summary/blob/master/LICENSE'
  x-tidepool-service: https://github.com/tidepool-org/summary

servers:
  - url: 'https://external.integration.tidepool.org'
    description: integration
  - url: 'https://api.tidepool.org'
    description: production
  - url: 'https://dev1.dev.tidepool.org'
    description: dev1
  - url: 'https://qa1.development.tidepool.org'
    description: qa1
  - url: 'https://qa2.development.tidepool.org'
    description: qa2

security:
  - sessionToken: []

tags:
  - name: Internal
    description: >-
      APIs intended for internal use by Tidepool.
  - name: Summary
    description: |-
      Summary Data

      This service was a prototype for separate service that calculates summary statistics for user accounts.
      It is replaced by additional APIs exposed by the `data` service, and executed by the `task` service.
      This documentation is for archival only.

paths:
  '/v1/summaries/{userId}':
    parameters:
      - $ref: ./common/parameters/tidepooluserid.yaml
    get:
      summary: Get User Summary
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Summary'
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: GetSummary
      description: Retrieve a summary by id
      tags:
        - Summary
        - Internal

components:
  schemas:
    Summary:
      $ref: ./summary/models/summary.v1.yaml
  securitySchemes:
    sessionToken:
      $ref: './common/security/tidepoolsessiontoken.v1.yaml'
    serverToken:
      $ref: './common/security/tidepoolservertoken.v1.yaml'
