openapi: 3.0.0
info:
  title: Data Summary API
  version: '1.0'
  description: 'Web service that stores summaries of user data'
  contact:
    name: Tidepool
    url: 'https://www.tidepool.org'
    email: support@tidepool.org
  license:
    name: BSD-2-Clause
    url: 'https://github.com/tidepool-org/clinic/blob/master/LICENSE'
  x-logo:
    url: 'https://github.com/tidepool-org/TidepoolApi/blob/master/assets/images/Tidepool_Logo_Light_Large.png'
    altText: Tidepool Logo
  x-tidepool-service: 'https://github.com/tidepool-org/clinic/'
servers:
  - url: 'http://localhost:8080'
    description: local development
  - url: 'https://dev1.dev.tidepool.org'
    description: dev1
  - url: 'https://qa1.development.tidepool.org'
    description: qa1
  - url: 'https://qa2.development.tidepool.org'
    description: qa2
  - url: 'https://external.integration.tidepool.org'
    description: integration
  - url: 'https://api.tidepool.org'
    description: production
paths:
  '/v1/summaries/{userId}/{summaryType}':
    parameters:
      - $ref: '#/components/parameters/userId'
      - $ref: '#/components/parameters/summaryType'
    get:
      summary: Get User Summary
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Summary'
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: GetSummary
      description: Retrieve a summary by user id
      x-internal: true
      tags:
        - summary

components:
  schemas:
    TidepoolUserId:
      $ref: './common/models/tidepooluserid.yaml'
    SummaryType:
      $ref: './summary/models/summarytype.v1.yaml'
    AverageGlucose:
      $ref: './data/models/blood/glucose/glucosemmol.v1.yaml'
    BGMBucketData:
      $ref: './summary/models/bgmbucketdata.v1.yaml'
    BGMPeriod:
      $ref: './summary/models/bgmperiod.v1.yaml'
    BGMPeriods:
      $ref: './summary/models/bgmperiods.v1.yaml'
    BGMStats:
      $ref: './summary/models/bgmstats.v1.yaml'
    CGMBucketData:
      $ref: './summary/models/cgmbucketdata.v1.yaml'
    CGMPeriod:
      $ref: './summary/models/cgmperiod.v1.yaml'
    CGMPeriods:
      $ref: './summary/models/cgmperiods.v1.yaml'
    CGMStats:
      $ref: './summary/models/cgmstats.v1.yaml'
    Bucket:
      $ref: './summary/models/bucket.v1.yaml'
    Config:
      $ref: './summary/models/config.v1.yaml'
    Dates:
      $ref: './summary/models/dates.v1.yaml'
    Summary:
      $ref: './summary/models/summary.v1.yaml'
  securitySchemes:
    sessionToken:
      $ref: './common/security/tidepoolsessiontoken.v1.yaml'
    serverToken:
      $ref: './common/security/tidepoolservertoken.v1.yaml'
  parameters:
    userId:
      name: userId
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/TidepoolUserId'
    summaryType:
      name: summaryType
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/SummaryType'
tags:
  - name: summary
    description: Tidepool Summary Data
security:
  - sessionToken: [ ]