type: object
title: config.v1
description: 'Summary schema version and calculation configuration'
properties:
  schemaVersion:
    description: Summary schema version
    type: number
    x-go-type: int
  highGlucoseThreshold:
    description: Threshold used for determining if a value is high
    type: number
    x-go-type: float64
  veryHighGlucoseThreshold:
    description: Threshold used for determining if a value is very high
    type: number
    x-go-type: float64
  lowGlucoseThreshold:
    description: Threshold used for determining if a value is low
    type: number
    x-go-type: float64
  veryLowGlucoseThreshold:
    description: Threshold used for determining if a value is very low
    type: number
    x-go-type: float64