name: check-and-publish

on:
  push:
    branches:
      - master

jobs:
  check:
    uses: ./.github/workflows/check.yml
    secrets: inherit

  publish:
    needs: [ check ]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
