name: check-and-publish-preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  check:
    if: github.event.action != 'closed' # Skip if closing the PR
    uses: ./.github/workflows/check.yml
    secrets: inherit

  publish_preview:
    needs: [ check ]
    uses: ./.github/workflows/publish_preview.yml
    secrets: inherit
    with:
      original_event_name: ${{ github.event_name }} 
      original_event_action: ${{ github.event.action }} 
