name: check-and-publish

on:
  workflow_dispatch:
  push:

jobs:
  check:
    uses: ./.github/workflows/check.yml
    secrets: inherit

  publish:
    needs: [ check ]
    uses: ./.github/workflows/publish.yml
    secrets: inherit
