# .github/workflows/deploy.yml
name: publish_public

on:
  workflow_call:

jobs:
  publish_public:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '>=16'
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19'
      - name: Build docs
      - run: |
            make install_tools check_tools public_static_docs
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./build/public/reference/docs/
          branch: gh-pages
          clean-exclude: pr-preview
          force: false
